trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6' 
    addToPath: true

- script: pip install -r requirements.txt
  displayName: 'Install required packages'

- script: flake8 --max-line-length=119 --exclude=.git/,__pycache__/,dist/ .
  displayName: "Run flake8"

- script: python -m pytest test/ --junitxml=./TEST-TEST.xml 
  displayName: 'Run tests'

- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TEST-*.xml'
  condition: succeededOrFailed()
